# $Header: /home/phv/CVSROOT/qc13_fltpt_sim/makefile,v 1.1.1.1 1999/02/22 18:14:21 djy Exp $
#Makefile for celp13k
CC=gcc
TTY_DIR=../ttylib
FXPTLIBS=../fxptlibs
CCINCDIR=-I$(TTY_DIR) -I$(FXPTLIBS)/ops
CCLIBDIR=-L$(TTY_DIR) -L$(FXPTLIBS)/ops
CFLAGS=-Wall -ansi $(CCINCDIR) $(CCLIBDIR) -DDOS=1
LINTFILES= ${SRC:.c=.ln}
#LINTFLAGS =  -hacbiu
#LINTFLAGS =  -hacb
CPPFLAGS = -I.
LINT = /usr/bin/lint
LDFLAGS = -lm -lc

SRC=\
	ratedec.c\
	cb.c\
	cb_tabs.c\
	celp13k.c\
	coderate.c \
	decode.c\
	encode.c \
	fer_sim.c\
	filter.c\
	frontfil.c\
	hammtab.c\
	io.c\
	init.c\
	log_10.c\
	lpc.c\
	lsp.c \
	modetabs.c\
	pack.c\
	pitch.c\
	postfilt.c\
	quantabs.c\
	quantize.c\
	snr.c\
	target.c

OBJ= ${SRC:.c=.o}

OBJDOS= ${SRCDOS:.c=.o}

all: celp13k

#.KEEP_STATE:

#all: celp13k_dos



celp13k:$(OBJ) $(TTY_DIR)/libtty.a $(FXPTLIBS)/ops/libops.a
	$(CC) $(CFLAGS) $(OBJ) -lm -ltty -lops -o $@

celp13k_dos:$(OBJDOS)
	$(CC) $(CFLAGS) $(OBJDOS) -lm -ltty -lops -o $@


celp13k.lint: ${LINTFILES}
	${LINT.c} -lm -lc ${LINTFILES}

clean:
	rm -f *.o

clobber:
	rm -f *.o celp13k celp13k.exe

$(OBJ): celp.h coder.h
fer_sim.o: fer_sim.h

